# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 52e5aa3ee9237eeb7aec902285edf033bc1a1cac9714a45b61f014338d92c60584eb4f2449b5a680e938ac478a163f8eb959f52f7ce8d157e24fa18638debbbb

test:
  secret_key_base: dd594356e9388ebf81df7607664eab415fbd84a1e1ca77167c1dde96a37cf4c1565a2bdad5b793018ecb8eb015687ff5fdc83dd2ade98c3b3796a96f4d1716f8

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
